### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by avarsh** [avarsh/square-robin#6]
Roadmap of features which should be implemented at some point.

## 0.1
- [ ] Usage of libraries such as JQuery, Handlebars and SASS to simplify code.
- [ ] Scheduling of projects

## 1.0
- [ ] Editing of tasks and projects
- [ ] First run help dialogs to explain different mechanics
- [ ] Instant task with an interface to add reminders
- [ ] Allowing adding of hobbies
- [ ] User configuration of various settings

## 2.0
- [ ] CSS tweaks and custom elements such as comboboxes and dates.
